"""add all models: User, Category, Address, Cart, Order, Listing, AdminActionLog, Plan, Subscription, ShippingMethod, etc

Revision ID: 9c33b7a90d48
Revises: 063b93101507
Create Date: 2025-11-07 13:19:50.310298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c33b7a90d48'
down_revision: Union[str, None] = '063b93101507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_items',
    sa.Column('faq_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del item de FAQ'),
    sa.Column('category', sa.String(length=100), server_default=sa.text("'General'"), nullable=True, comment='Categoría o tema de la pregunta frecuente'),
    sa.Column('question', sa.Text(), nullable=False, comment='Texto de la pregunta frecuente'),
    sa.Column('answer', sa.Text(), nullable=False, comment='Texto de la respuesta a la pregunta'),
    sa.Column('display_order', sa.SmallInteger(), nullable=True, comment='Orden de visualización del item en la lista de FAQs'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_table('legal_documents',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador unico del documento legal'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="Indentificador amigable para URLs (ej: 'terms-of-service)"),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Titulo del documento legal'),
    sa.Column('content', sa.Text(), nullable=False, comment='Contenido completo del documento legal'),
    sa.Column('version', sa.Float(), server_default='1.0', nullable=False, comment='Numero de version del documento (ej: 1.0, 1.1)'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del documento'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('plans',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del plan'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre del plan de suscripción'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio del plan'),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billingcycle'), nullable=False, comment='Ciclo de facturación: monthly, quarterly o yearly'),
    sa.Column('features_json', sa.String(), nullable=True, comment='Características y límites del plan en formato JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_action_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador unico del log de accion administrativa'),
    sa.Column('admin_id', sa.UUID(), nullable=True, comment='UUID del administrador que ejecutó la acción'),
    sa.Column('action_type', sa.String(length=100), nullable=False, comment='Tipo de accion admnistrativa realizada'),
    sa.Column('target_entity_type', sa.String(length=50), nullable=True, comment='Tipo de entidad afectada por la accion (ej. LISTING_REJECTED, REPORT_RESOLVED, USR_BLOCKED)'),
    sa.Column('target_entity_id', sa.Integer(), nullable=True, comment='ID de la entidad afectada'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Razon o descripcion detallada de la accion admnistrativa'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora en que se registro la accion'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('shipping_methods',
    sa.Column('method_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único para el método de envío.'),
    sa.Column('seller_id', sa.UUID(), nullable=False, comment='UUID del vendedor que ofrece este método.'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Nombre descriptivo (ej. 'Recojo en taller')."),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='El precio que será agregado a la orden si este método es escogido.'),
    sa.Column('type', sa.Enum('PICKUP', 'DELIVERY', name='shipping_type_enum', create_constraint=True), nullable=False, comment="Define si es para recojo ('pickup') o para envío a casa ('delivery')."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('method_id')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la Suscripción'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='UUID del usuario suscrito'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='Llave foranea a la tabla de planes (plans)'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CANCELLED', name='suscription_status_enum', create_constraint=True), nullable=False, comment='Estatus actual de la suscripcion (e.g., ACTIVE, INACTIVE, CANCELLED).'),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de inicio de la suscripcion'),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=False, comment='Fecha del proximo cobro de la suscripcion'),
    sa.Column('gateway_sub_id', sa.String(length=255), nullable=False, comment='ID unico de la suscripcion en la pasarela de pago'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('gateway_sub_id'),
    sa.UniqueConstraint('user_id', 'plan_id', name='unique_user_plan')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('listing_shipping_options',
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='ID del listing al que aplica esta opción de envío'),
    sa.Column('method_id', sa.Integer(), nullable=False, comment='ID del método de envío disponible para este listing'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['shipping_methods.method_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'method_id'),
    comment='Tabla pivote que conecta listings con métodos de envío disponibles'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_shipping_options')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('shipping_methods')
    op.drop_table('admin_action_logs')
    op.drop_table('plans')
    op.drop_table('legal_documents')
    op.drop_table('faq_items')
    # ### end Alembic commands ###
